### ISSUE TITLE
Problema no processamento de regras com tipo objetos JSON Extended

### ISSUE THREAD

**Issue by vivaldomp** [bancodobrasil/featws-ruller#69]
Na chamada de execução de uma regra do tipo 0043 - return_json_extended_format via (case do featws-transpiler) à api do ruller não é devolvido estruturas de objetos json com mais de 1 nível (árvore de objetos). Exemplo de resposta atualmente:

![Screenshot from 2022-10-14 13-13-02](https://user-images.githubusercontent.com/10130162/195892947-d8bb8c57-a61e-4db9-81be-b96163a70805.png)

Regra: https://canais.fontes.intranet.bb.com.br/cfe/cfe-featws-rules-dev-apw-teste/
Item de regra com problema: APW_SIDEBAR_OPTIONS

**Comment by aaugustogv** [comment]
Issue duplicada, tratamos na issue bancodobrasil/featws-api#54
