### ISSUE TITLE
[Ruller] Fechando PR's

### ISSUE THREAD

**Issue by eduardacastro** [bancodobrasil/featws-ruller#84]
- [x] Arrumando erro no ReadMe:
      link pull request: https://github.com/bancodobrasil/featws-ruller/pull/61

- [x] Arrumando erros de PT-BR no ReadMe:
      link pull request: https://github.com/bancodobrasil/featws-ruller/pull/82

- [x] Arrumando erros de PT-BR no ReadMe:
      link pull request: https://github.com/bancodobrasil/featws-ruller/pull/83

**Comment by aaugustogv** [comment]
https://github.com/bancodobrasil/featws-agile/issues/106
